### ISSUE TITLE
New Querys

### ISSUE THREAD

**Issue by jeetelongname** [meain/evil-textobj-treesitter#2]
Hi so I am currently working on [tree sitter support for doom emacs](https://github.com/hlissner/doom-emacs/pull/5401) and i was wondering if you would accept PR's for new querys or if you would prefer them to be upstreamed to neovim? 

as far as I am seeing its just a matter of adding the query to the textobjs.scm and it should work :tm: but I could be very wrong.

Thanks for any input you could have

**Comment by meain** [comment]
This is great.

If it is beneficial for both projects, I think it would be better if it is upstreamed to nvim-treesitter/nvim-treesitter-textobjects. I can just pull from there. No point in duplicating the effort.

As for adding new text objects, it is pretty much just adding more items to the `textobjs.scm` file for each lang. At least that is the case here and from what I can understand the same for the neovim package as well.

If for any case, there is Emacs specific things or they don't wanna add things in(which I highly doubt will be the case) we can always add it in this project.

**Comment by meain** [comment]
I am also working on something that will let you use custom queries. Probably not what you will need, but just wanted to point it out.
ref: https://github.com/meain/evil-textobj-treesitter/pull/1

**Comment by jeetelongname** [comment]
I was just trying to even out the coverage of text objects but I have been checking out that PR and it looks really cool! Ill go and upstream them and let you know when they are merged. Thanks for your help!
